name: furo

on:
  workflow_dispatch:
  push:
    branches:
      - deploy

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: Checkout Code
        uses: actions/checkout@v3

      # setup nodejs
      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # npm install
      - name: Install Deps
        run: npm install --force

      # build project
      - name: Build Project
        run: npm run build

      # Deploy project
      - name: Deploy Project to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true
          enable_jekyll: true

  copy-files-to-build:
    needs: [gh-pages]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Copy To Branches Action
        uses: planetoftheweb/copy-to-branches@v1.3
        env:
          key: deploy
          files: index.html
